mex -v mxGetMessages.c
mex -v mxUpdateStatus.c
mex -v mxGetProjectName.c
mex -v mxGetStartTime.c
mex -v mxGetTime.c
mex -v mxSetTime.c
mex -v mxCreateBus.c
mex -v mxListBuses.c
mex -v mxGetBus.c
mex -v mxGetBuses.c
mex -v mxUpdateBus.c
mex -v mxDeleteByIndex.c
mex -v mxDeleteByTime.c
mex -v mxDeleteBus.c
mex -v mxDisplayBus.c
mex -v mxHideBus.c
mex -v mxListCanvases.c
mex -v mxUpdateOverlay.c
mex -v mxComputeFixations.c
mex -v mxGetFixations.c
mex -v mxUpdateFixations.c
mex -v mxGetRoiState.c
mex -v mxGetRois.c
mex -v mxGetRoiIntersections.c
mex -v mxGetInterpolatedRoiFrames.c
mex -v mxSignOffClient.c

mex -v mxActivateOptoTrigger.c
mex -v mxCancelOptoTrigger.c
mex -v mxLoadOptoProject.c
mex -v mxUpdateOptoDot.c
mex -v mxDeleteOptoDot.c
mex -v mxReloadOptoTransform.c
mex -v mxToggleOptoPlayMode.c
mex -v mxResetOptoTime.c
